"""add email to user

Revision ID: 5638375a53f1
Revises: 5fb8bba2c373
Create Date: 2025-08-11 04:15:08.938960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import letta


# revision identifiers, used by Alembic.
revision: str = '5638375a53f1'
down_revision: Union[str, None] = '5fb8bba2c373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), server_default='', nullable=False))
        batch_op.create_unique_constraint('uq_users_email', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_column('email')
    # ### end Alembic commands ###
