"""add password to user

Revision ID: 840c1889f00c
Revises: 5638375a53f1
Create Date: 2025-08-11 04:16:17.797095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import letta


# revision identifiers, used by Alembic.
revision: str = '840c1889f00c'
down_revision: Union[str, None] = '5638375a53f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column('password')
    # ### end Alembic commands ###
