"""add role to user

Revision ID: c08b7c7b3d89
Revises: 840c1889f00c
Create Date: 2025-08-11 04:17:30.689173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import letta


# revision identifiers, used by Alembic.
revision: str = 'c08b7c7b3d89'
down_revision: Union[str, None] = '840c1889f00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), server_default='User', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column('role')
    # ### end Alembic commands ###
